apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-server-pod-deploy
  labels:
    name: result-server-pod-deploy
    app: phonebook-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: result-server-pod
      app: phonebook-app
  template:
    metadata:
      name: result-server-pod
      labels:
        name: result-server-pod
        app: phonebook-app
    spec:
      containers:
      - name: result-server
        image: aydintokuslu/phonebook_resultserver:5.0
        ports:
            - containerPort: 80
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        envFrom:
          - configMapRef:
              name: servers-configmap
        resources:
            limits:
              memory: 500Mi
              cpu: 100m
            requests:
              memory: 250Mi
              cpu: 80m