apiVersion: v1
kind: Service
metadata:
  name: result-server
  labels:
    name: result-server
    app: phonebook-app
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort
  #type: LoadBalancer
  selector:
     name: result-server-pod
     app: phonebook-app