apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
    app: phonebook-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: mysql-pod
      app: phonebook-app
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
        app: phonebook-app
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        envFrom:
          - configMapRef:
              name: database-configmap
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim