apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp-deploy
  name: webapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: webapp-deploy
    spec:
      containers:
      - image: aydintokuslu/simple-webapp:1.0
        name: webapp
        ports:
          - containerPort: 8080
