apiVersion: v1
kind: Service
metadata:
  name: webapp-delayed-service
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30100
  selector:
     app: webapp-delayed
  type: NodePort