apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    name: web-server-service
    app: phonebook-app
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30011
  type: NodePort
  #type: LoadBalancer
  selector:
     name: web-server-pod
     app: phonebook-app