apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstore-api-pv-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/Users/aydin/Desktop/Kubernetes/203-dockerization-bookstore-api-on-python-flask-mysql"