apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UjEyMzRy
  MYSQL_PASSWORD: Q2xhcnVzd2F5XzE=


  # myrootpassword: UjEyMzRy
  # mypassword: Q2xhcnVzd2F5XzE=



# Clarusway_1 ve R1234r şifreleri önce encode edilmeli bunun için
#echo -n 'R1234r' | base64   --->  mysql-root-password olarak mysql-secret.yaml dostasında adreslenir
#echo -n 'CLarusway_1' | base64 ----> mysql-admin-password olarak mysql-secret.yaml dostasında adreslenir

# Clarusway_1 ve R1234r şifreleri decode etmek için
# echo -n 'UjEyMzRy' | base64 --decode     ---> It gives root us poassword
# echo -n 'Q2xhcnVzd2F5XzE=' | base64 --decode   ---> It gives us admin password