apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: R1234r
        - name: MYSQL_USER
          value: Clarusway_1
        - name: MYSQL_PASSWORD
          value: clarus
        - name: MYSQL_DATABASE
          value: phonebook
        resources: {}

