apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver
  name: resultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver
  strategy: {}
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - image: aydintokuslu/proje_resultserver
        name: resultserver
        ports:
        - containerPort: 80
        env: 
        - name: MYSQL_DATABASE_HOST
          value: mysql
        - name: MYSQL_USER
          value: clarus
        - name: MYSQL_PASSWORD
          value: Clarusway_1
        - name: MYSQL_DATABASE
          value: phonebook
        resources: {}

